### ISSUE TITLE
not working using TABs

### ISSUE THREAD

**Issue by ericblade** [rubymaniac/vscode-paste-and-indent#2]
It installs, but even after restarting, I get no pasteAndIndent.action command.  It seems like it might recognize it, as it starts capitalizing pasteAndIndent in that form, regardless of what case i enter the letters in, but it doesn't give me an autofill, and it just does nothing if I enter the whole string.

**Comment by rubymaniac** [comment]
The command is not exposed to the command palette so what you are trying to do is not going to work. Try binding the command to a key combination inside your **keybindings.json** file. Here is an example keybindings file https://github.com/rubymaniac/vscode-paste-and-indent#usage. 

Sorry if it wasn't clear from the documentation that there is no command palette integration.

**Comment by ericblade** [comment]
I tried binding it to an open key combo (win+v), as well as to override the default paste (ctrl+v), and got nothing there either.

Yeah, not real clear from the documentation that it wouldn't show up in the commands list .. i guess unless someone has knowledge that not all commands may show up there?  To wit:

> This extension provides one command:
> pasteAndIndent.action

tells me I should be able to run it from the command list too .. but i didn't know it was possible for a command to not appear in the list.  In any case, selecting something, copying with ctrl+c, then attempting to paste using a key command doesn't seem to work.

**Comment by rubymaniac** [comment]
Hmm then it might be a Windows thing. I will look into it (after I find a windows machine) and I will let you know.

**Comment by CherryDT** [comment]
Not working for me either - the command appears to do the same as normal pasting (I bound it to ctrl+shift+v), and the `pasteAndIndent.selectAfter` setting is not recognized (warning about unknown setting).

Version 1.9.0-insider
Commit 83db3cad0c9a05dac75a7472b3b81b39ace243f7
Date 2017-01-06T07:10:22.163Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

I'm on Windows 10 Build 14986.

**Comment by rubymaniac** [comment]
@CherryDT I will look into it probably tomorrow and will let you know. Thanks

**Comment by rubymaniac** [comment]
@CherryDT can you please post your *keybindings.json*?

**Comment by CherryDT** [comment]
```
// Place your key bindings in this file to overwrite the defaults
[
	{ "key": "shift+f1", "command": "extension.devDocs", "when": "editorTextFocus" },
	{ "key": "ctrl+shift+v", "command": "pasteAndIndent.action", "when": "editorTextFocus && !editorReadonly" }
]
```

However, I just noticed that it does appear to do _something_: When I use Ctrl+V, and I press Ctrl+Z, it undoes the paste. However, if I use Ctrl+Shift+V (your plugin) and then Ctrl+Z, it does nothing, only after pressing Ctrl+Z a second time, it undoes the paste... (no indention though whatsoever)

**Comment by rubymaniac** [comment]
@CherryDT can you please provide an example with an expected and actual indentation?

**Comment by CherryDT** [comment]
I just found out that depending on where exactly you paste it, it *does* do something, albeit not the right things.

```
function(a) {
	function(b) {
		function(c) {
			function(d) {
				function(e) {

				}
			}
		}
	}
}

function(a) {
	function(b) {
		// vvv THIS part vvv
		function(c) {
			function(d) {
				function(e) {
					
				}
			}
		}
		// ^^^ THIS part ^^^
	}
	// <<< copied to here
}

function(a) {
	function(b) {
		function(c) {
			function(d) {
				function(e) {

				}
			}
		}
	}
	function(c) { // <<< EXPECTED result in all cases below
		function(d) {
			function(e) {

			}
		}
	}
}

function(a) {
	function(b) {
		function(c) {
			function(d) {
				function(e) {
					
				}
			}
		}
	}
		function(c) { // <<< this happens when selecting the whole empty line before pasting (as I used to do in Sublime Text)
			function(d) {
				function(e) {
					
				}
			}
		}
}

function(a) {
	function(b) {
		function(c) {
			function(d) {
				function(e) {

				}
			}
		}
	}
		function(c) { // <<< this happens when pasting into an empty line (without any tabs in it)
			function(d) {
				function(e) {

				}
			}
		}
// <<< this time there is an empty line here
}

function(a) {
	function(b) {
		function(c) {
			function(d) {
				function(e) {

				}
			}
		}
	}
	function(c) { // <<< this happens when the cursor is at the end of the line (after the tab) before pasting
	function(d) { // <<< this is the ONLY TIME that something is selected afterwards (with selectAfterPaste enabled)! however, the selection starts at this SECOND line only...
		function(e) {

		}
	}
	}
// <<< selection ends here in this empty line (and here is the cursor)
}

```

Basically, I was expecting it to work like it does in Sublime Text when using Ctrl+Shift+V, but it appears to do all kinds of weird things instead...

**Comment by CherryDT** [comment]
@rubymaniac here I recorded a video of what happens in Sublime Text (what I expect) vs what happens with your extension in VSCode, which demonstrates the cases above + 2 more: http://recordit.co/Q5aYxf5VCy

**Comment by rubymaniac** [comment]
@CherryDT yes I can reproduce this weird behavior (it is present everywhere not only on Windows). It seems that it cannot handle TABS well. I will look into it ASAP and will push a fix! Thanks a lot for the find!

**Comment by rubymaniac** [comment]
@CherryDT I have pushed a fix for this please try it out

**Comment by CherryDT** [comment]
@rubymaniac:
You fixed indentation in the "copying to the end of a line with whitespace before" case, but the other cases I demonstrated in the video are not fixed, just changed - I get it now at the beginning of the line. Also, it still selects only from the second pasted line to the last, not from the first.

**Comment by rubymaniac** [comment]
> I get it now at the beginning of the line

Currently it doesn't support syntax checking in order to know exactly the offset at which the paste has to happen. It simply pastes and indents to where your **cursor** is. If it is at the start of the line it will paste at the start of the line.

> Also, it still selects only from the second pasted line to the last, not from the first.

This is expected. `selectAfter` option is meant to be used for languages where whitespace is used to delimit scopes instead of special tokens (e.g. Python).

So in order to solve your problems just place your cursor where you want to paste and disable `selectAfter`.

**Comment by CherryDT** [comment]
Hm, I see...

I would be most happy if the following two things could be added, though:

- An action which allows to paste at the same indention level as the line above the current line has.
- An option to select everything pasted *including* the first line, so the indentation of whole block can be easily changed afterwards using (Shift+)Tab.

The first would cover most of my usual scenarios, and in the few cases where it doesn't, it can be easily fixed with the second.

If this feature request could be considered, it would be really helpful to me, because this functionality which "just works" without requiring positioning the cursor specifically is something which I miss the most from Sublime Text.

Thank you for your effort!

(If there is no way this will be added, I might try and get into VSCode extension development too... just for that.)

**Comment by rubymaniac** [comment]
Yes I think those are fairly easy to implement and actually the first in your list is in my TODO list (I just haven't had the time to implement it). I will give them a try and update this thread.

Cheers!
